---

# hub command

- name: check hub installed
  command: which hub
  register: which_hub
  failed_when: no
  changed_when: which_hub.rc != 0

- name: check hub version
  when: which_hub is not changed
  command: hub --version
  register: hub_ver
  failed_when: no
  changed_when: |
    ('hub version ' + hub_version) != hub_ver.stdout_lines[1]

- name: install or update hub
  when: which_hub is changed or hub_ver is changed
  block:
    - name: create temporary file
      tempfile:
        state: directory
      register: tempdir

    - name: download hub binary
      unarchive:
        remote_src: yes
        src: "{{ hub_url }}"
        dest: "{{ tempdir.path }}"

    - name: install hub with man
      script: "{{ tempdir.path }}/hub-linux-amd64-{{ hub_version }}/install"
      become: yes

    - name: add fish completions
      copy:
        src: "{{ tempdir.path }}/hub-linux-amd64-{{ hub_version }}/etc/hub.fish_completion"
        dest: ~/.config/fish/completions/hub.fish

    - name: set hub profile
      copy:
        src: hub.sh
        dest: "{{ bash_profile_dir }}"
        mode: a+x
