---
# hub command
- name: install hub
  command: go get -v -u github.com/github/hub
  register: hub_update
  changed_when: |
    'github.com/github/hub' in hub_update.stderr_lines[-1]

- name: set hub profile
  copy:
    src: hub.sh
    dest: "{{ bash_profile_dir }}"
    mode: a+x
